version: "3.0"
services:
  extremely_vulnerable_flask_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: iast
      args:
        IMMUNITY_HOST: "127.0.0.1"
        IMMUNITY_PORT: "81"
        IMMUNITY_PROJECT: "vuln_vulnerable-flask-app"
    network_mode: "host"
    ports:
      - 5000:88
